# BetterFood Version 0.9.1Dev #
#       Messages Config       #
###############################
Title: Health Stats
#Names of the Balance (colors are NOT changeable)
Hydration: Hydratation
Carbohydrates: Carbohydrates
Protein: Proteinas
Vitamin: Vitaminas
