name: BetterFood
main: com.cadiducho.dev.BetterFood.main.BetterFood
version: '0.9.8'
description: Estadisticas sobre tu salud alimenticia
author: Cadiducho
commands:
  salud:
    description: Ver tu salud alimenticia
    aliases: [health, betterfood]