name: BetterFood
main: com.cadiducho.dev.BetterFood.main.BetterFood
version: '1.0Beta'
description: Estadisticas sobre tu salud alimenticia
author: Cadiducho
commands:
  salud:
    description: Ver tu salud alimenticia
    aliases: [health, betterfood]