name: BetterFood
main: com.cadiducho.dev.BetterFood.BetterFood
version: '2.0Beta'
description: Estadisticas sobre tu salud alimenticia
author: Cadiducho
commands:
  salud:
    description: Ver tu salud alimenticia
    aliases: [health]
  betterfood:
    description: BetterFood Admin Command
    aliases: [bf, healthadmin]
